# -*- coding: utf-8 -*-
"""Analyze_this.ipynb

Automatically generated by Colaboratory.

Original file is located at
	https://colab.research.google.com/drive/1HFudXN7l1Pkt5s7F8xSWlvU1ZybEV1fE
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
import sys

from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from xgboost.sklearn import XGBClassifier

from sklearn.decomposition import PCA

traindf = pd.read_csv('development_dataset.csv')

r, c = traindf.shape
print(r,c)

"""### Preprocessing"""

def preprocessing(traindf):
	for col in traindf.columns:
		if col not in ['VAR14','VAR18','VAR19','VAR21']:
			coldata = traindf[col];
			coldata[coldata.isna()] = coldata.mean();

	mode = traindf['VAR14'].mode()[0];
	traindf['VAR14'] = traindf['VAR14'].str.replace('.',mode);
	traindf['VAR14'] = traindf['VAR14'].astype(float)

	for col in traindf.columns:
		pd.to_numeric(traindf[col],errors='coerce')
	y_status=traindf['VAR21'].values    
	retDropDict = {'Low':0,'Medium':1,'High':2}
	y1 = np.array([retDropDict[i] for i in y_status])
	traindf['result']=y1

preprocessing(traindf);
traindf.head()

"""### Feature Engineering"""
def split(traindf,ratio = 0):
	colFeatureResult = ['VAR' + str(i) for i in range(2,21)];
	if(ratio > 0.0):
		x_train, x_test, y_train, y_test = train_test_split(traindf[colFeatureResult],traindf["result"], test_size=ratio, random_state=42)

		for column in x_train.columns:
			pd.to_numeric(x_train[column])

		return [x_train,y_train,x_test,y_test]
	if(ratio == 0.0):
		x_train = traindf[colFeatureResult];
		y_train = traindf["result"];
		for column in x_train.columns:
			pd.to_numeric(x_train[column])

		return [x_train,y_train]

'''
[x_train,y_train,x_test,y_test] = split(traindf,ratio = 0.1)
print(x_train.head())
'''

[x_train,y_train] = split(traindf,ratio = 0.0)




scaler = StandardScaler()
scaler.fit(x_train);
x_train = scaler.transform(x_train);

pca = PCA(n_components= 19, svd_solver='full')
pca.fit(x_train);
print(pca.explained_variance_ratio_)  ;

x_train = pca.transform(x_train)

estimator = XGBClassifier( learning_rate =0.05, n_estimators=500, max_depth=7,
 min_child_weight=1, gamma=0.1, subsample=0.85, colsample_bytree=0.85,
 objective= 'binary:logistic', nthread=4, scale_pos_weight=1,seed=27)

estimator.fit(x_train,y_train)
print(estimator.score(x_train,y_train))

leaderdf = pd.read_csv('leaderboard_dataset.csv')

for col in leaderdf.columns:
	if col not in ['VAR14','VAR18','VAR19','VAR21']:
		coldata = leaderdf[col];
		coldata[coldata.isna()] = coldata.mean();

mode = leaderdf['VAR14'].mode()[0];
leaderdf['VAR14'] = leaderdf['VAR14'].str.replace('.',mode);
leaderdf['VAR14'] = leaderdf['VAR14'].astype(float)

for col in leaderdf.columns:
	pd.to_numeric(leaderdf[col],errors='coerce')

colFeatureResult = ['VAR' + str(i) for i in range(2,21)];
result = estimator.predict(pca.transform(scaler.transform(leaderdf[colFeatureResult])));
res_dictionary = {0:"Low", 1:"Medium", 2:"High"};
result = [res_dictionary[i] for i in result];
output = pd.DataFrame(leaderdf['VAR1'].values)
output["result"] = pd.DataFrame(result);

output.to_csv('InnerPeace_IITMadras_5.csv')


'''
leaderdf = pd.read_csv('leaderboard_dataset.csv')
def testing(estimator,leaderdf):
	for col in leaderdf.columns:
		if col not in ['VAR14','VAR18','VAR19','VAR21']:
			coldata = leaderdf[col];
			coldata[coldata.isna()] = coldata.mean();

	mode = leaderdf['VAR14'].mode()[0];
	leaderdf['VAR14'] = leaderdf['VAR14'].str.replace('.',mode);
	leaderdf['VAR14'] = leaderdf['VAR14'].astype(float)

	for col in leaderdf.columns:
		pd.to_numeric(leaderdf[col],errors='coerce')

	colFeatureResult = ['VAR' + str(i) for i in range(2,21)];
	result = estimator.predict(leaderdf[colFeatureResult]);
	res_dictionary = {0:"Low", 1:"Medium", 2:"High"};
	result = [res_dictionary[i] for i in result];
	output = pd.DataFrame(leaderdf['VAR1'].values)
	output["result"] = pd.DataFrame(result);

	output.to_csv('InnerPeace_IITMadras_2.csv')

testing(estimator,leaderdf)
'''